targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale
          input_directory: assets/translations
          input_file_pattern: .json
          output_directory: lib/i18n
          timestamp: false
